### ISSUE TITLE
hello , greet work

### ISSUE THREAD

**Issue by itsho15** [bayareawebpro/wp-lumen-plugin-framework#3]
when i use your example in 
https://github.com/bayareawebpro/wp-lumen-plugin-framework/wiki/Database-Table-Management

i got an error __construct function not able to show the $panel_attributes var 
from where you type This $panel_attributes ? 
it`s a public var you injected automatically ? 
or what i got error called 

Unresolvable dependency resolving [Parameter #2 [ <required> $panel_attributes ]] in class App\Http\Controllers\Admin\DatabaseController

**Comment by bayareawebpro** [comment]
Sorry about that.  I shared that example from my personal working copy.  Yes, you can simply remove that.   I was using injection to pass the panel attributes from the WpHelper class.  
You can add a line to the addPanel method:

$this-app
->when($closure)
->needs('$panel_attributes')
->give(compact(func_get_args()));

https://github.com/bayareawebpro/wp-lumen-plugin-framework/blob/master/app/Helpers/WpHelper.php#L182
