### ISSUE TITLE
Call to undefined function FastRoute\simpleDispatcher()

### ISSUE THREAD

**Issue by piotrkochan** [bayareawebpro/wp-lumen-plugin-framework#4]
I always have an error:

```
Call to undefined function FastRoute\simpleDispatcher()
```

I've tried to update Lumen but error is still the same. It occurs in `vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php`:

```
protected function createDispatcher()
    {
        return $this->dispatcher ?: \FastRoute\simpleDispatcher(function ($r) {
            foreach ($this->router->getRoutes() as $route) {
                $r->addRoute($route['method'], $route['uri'], $route['action']);
            }
        });
    }
```

I've even tried to add `nikic/FastRoute` to composer.json but it does not help.

**Comment by bayareawebpro** [comment]
I was not able to reproduce this issue.  I just downloaded a fresh copy and did a composer install and it's working fine.  PHP version 7.2.8

**Comment by piotrkochan** [comment]
I use PHP 7.1 and Wordpress 4, you?

**Comment by piotrkochan** [comment]
@bayareawebpro did You just cloned repo and ran composer install? In this case yes, it works but did You tried to install it as a wp plugin and enable it?

**Comment by bayareawebpro** [comment]
Lumen requires "7.1**.3**" or Greater.

**Comment by piotrkochan** [comment]
I tried it on other machine (Linux) and it worked while on Macbook it does't. I'm closing it now.
