### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by itsho15** [bayareawebpro/wp-lumen-plugin-framework#5]
how can i work with validation < when i try to validate data it`s not return back 

still in the same page and i don`t know why 

$this->validate($this->request, [
				'journal_author'       => 'required|string',
				'journal_organization' => 'required|string',
				'journal_authors'      => 'required|string',
				'journal_issued_date'  => 'required|date',
				'journal_title'        => 'required|string',
				'journal_abstract'     => 'required|string',
				'journal_name'         => 'required|string',
				'journal_website'      => 'required|url',
				'journal_keywords'     => 'required|string',
]);

this is my code in update method 

but it must redirect back and handle the errors from

@if (count($request->errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($request->errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

and other question

about sessions

session()->flash not work only work session()->put

can u help me ?

**Comment by bayareawebpro** [comment]
I couldn't get session->flash() to work.  Not sure why.  And as for validation I only use Vue / Ajax for for requests so I'm not sure why it's not working for you.  I'm sorry I can't be of more help.   If you figure it out please send submit a pull request.  Thanks.
