### ISSUE TITLE
Table 'wp_wplumen_sessions' doesn't exist 

### ISSUE THREAD

**Issue by gaz-think3** [bayareawebpro/wp-lumen-plugin-framework#6]
Base table or view not found: 1146 Table 'wp-test.wp_wplumen_sessions' doesn't exist. Whenever I attempt to install and activate the plugin it throw the following error and I am not sure why?

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wp-test.wp_wplumen_sessions' doesn't exist (SQL: select * from `wp_wplumen_sessions` where `id` = vFsao8hug2TQuXxhwnwcL2tjUqZrSiOlvGCtcS limit 1)`

When the plugin is activate it calls `<?php namespace App\Utilities;
class Activate{

    /**
     * @var $app \Laravel\Lumen\Application
     * @var $config \Illuminate\Config\Repository
     * @var $artisan \Illuminate\Contracts\Console\Kernel
     * @var $schema \Illuminate\Database\Schema\Builder
     */
    protected $app, $config, $artisan, $schema;

    /**
     * Class Initialization called by Hook (Requires Static Method)
     * @return self
     */
    public static function init()
    {
        putenv('APP_ENV=staging');
        return new self();
    }

    /**
     * Class Constructor called by init()
     */
    public function __construct()
    {
        $this->app = \App\Helpers\LumenHelper::plugin();
        $this->config = $this->app->make('config');
        $this->artisan = $this->app->make(\Illuminate\Contracts\Console\Kernel::class);
        $this->schema = $this->app->make('db')->connection('wp')->getSchemaBuilder();
        $this->schema();
        $this->data();
    }

    /**
     * Modify Database Schema
     */
    public function schema()
    {
        if($this->config->get('session.driver', 'file') === 'database'){
            $this->artisan->call('migrate:install');
            $this->artisan->call('migrate');
        }
    }

    /**
     * Insert Database Data
     */
    public function data()
    {

    }

}`

Which you would assume creates the tables by hooking into the wordpress DB. Any ideas are welcome.

**Comment by bayareawebpro** [comment]
You might need to use the config to temporarily set the session driver to file during migration.
`
if($this->config->get('session.driver', 'file') === 'database'){
        $this->config->put('session.driver', 'file');
        $this->artisan->call('migrate:install');
        $this->artisan->call('migrate');
        // wait for redirect to occur which will reset the config value to database.
}
`
